### ISSUE TITLE
2.0.0 Broke Multiple Consumers on same groupId?

### ISSUE THREAD

**Issue by leppaott** [tulios/kafkajs#1371]
Any idea, we just added second instance that on startup tries to subscribe to topics on same groupId (with different clientId) and after rebalancing it just stops - both instances... Just figured it out that 1.6.0 works fine. Tried everything from createTopics numPartitions etc. and Default/JavaPartitioner.

They both try to subscribe to 2 topics that are created by either of the instances.
     

> {"level":"INFO","timestamp":"2022-05-24T10:20:48.612Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"node-metadata","memberId":"2780d1261b54-b1c8d023-ea90-44f8-ab0b-4a50659bfb63","leaderId":"76dd55c83700-ea906348-063f-46ba-be20-20ad585a6d69","isLeader":false,"memberAssignment":{"service.topicA":[0]},"groupProtocol":"RoundRobinAssigner","duration":2310}

> {"level":"ERROR","timestamp":"2022-05-24T10:20:53.640Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"2780d1261b54","error":"The group is rebalancing, so a rejoin is needed","correlationId":9,"size":10}

> {"level":"WARN","timestamp":"2022-05-24T10:20:53.640Z","logger":"kafkajs","message":"[Runner] The group is rebalancing, re-joining","groupId":"node-metadata","memberId":"2780d1261b54-b1c8d023-ea90-44f8-ab0b-4a50659bfb63","error":"The group is rebalancing, so a rejoin is needed"}

> {"level":"INFO","timestamp":"2022-05-24T10:20:53.645Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"node-metadata","memberId":"2780d1261b54-b1c8d023-ea90-44f8-ab0b-4a50659bfb63","leaderId":"2780d1261b54-b1c8d023-ea90-44f8-ab0b-4a50659bfb63","isLeader":true,"memberAssignment":{"service.topicA":[0],"service.topicB":[0]},"groupProtocol":"RoundRobinAssigner","duration":5}

> {"level":"INFO","timestamp":"2022-05-24T10:20:53.648Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"node-metadata"}

**Comment by Nevon** [comment]
I believe this is due to #1361, which was fixed in v2.0.1. Could you try that version and see if you get the same issue?

**Comment by leppaott** [comment]
Oh yeah was about to say 2.0.1 looked promising but still the same problem.

Any other way to debug this?

Kafka shows explicit LeaveGroup, that is intended?
>  | [2022-05-24 10:59:28,454] INFO [GroupCoordinator 1]: Preparing to rebalance group node-metadata in state PreparingRebalance with old generation 2 (__consumer_offsets-42) (reason: Removing member 5ef6c1589178-e164ddee-57c1-41ce-96cc-4df6303cbead on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2022-05-24 10:59:28,465] INFO [GroupCoordinator 1]: Member MemberMetadata(memberId=5ef6c1589178-e164ddee-57c1-41ce-96cc-4df6303cbead, groupInstanceId=None, clientId=5ef6c1589178, clientHost=/172.18.0.12, sessionTimeoutMs=30000, rebalanceTimeoutMs=60000, supportedProtocols=List(RoundRobinAssigner)) has left group node-metadata through explicit `LeaveGroup` request (kafka.coordinator.group.GroupCoordinator)

**Comment by Nevon** [comment]
Try running with debug log level and see what we can learn from that. https://kafka.js.org/docs/configuration#logging

**Comment by leppaott** [comment]
Not much wiser.

> {"level":"DEBUG","timestamp":"2022-05-24T11:45:51.184Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 11)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":0,"size":169,"data":"[filtered]"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.189Z","logger":"kafkajs","message":"[Connection] Request Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":10,"expectResponse":true,"size":98}
{"level":"ERROR","timestamp":"2022-05-24T11:45:51.191Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","error":"The group is rebalancing, so a rejoin is needed","correlationId":10,"size":10}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.192Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","error":"The group is rebalancing, so a rejoin is needed","correlationId":10,"payload":{"type":"Buffer","data":"[filtered]"}}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.193Z","logger":"kafkajs","message":"[Connection] Request Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":11,"expectResponse":true,"size":98}
{"level":"ERROR","timestamp":"2022-05-24T11:45:51.195Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","error":"The group is rebalancing, so a rejoin is needed","correlationId":11,"size":10}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.195Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","error":"The group is rebalancing, so a rejoin is needed","correlationId":11,"payload":{"type":"Buffer","data":"[filtered]"}}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.196Z","logger":"kafkajs","message":"[FetchManager] Stopping fetchers..."}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.196Z","logger":"kafkajs","message":"[FetchManager] Stopped fetchers"}
{"level":"WARN","timestamp":"2022-05-24T11:45:51.196Z","logger":"kafkajs","message":"[Runner] The group is rebalancing, re-joining","groupId":"node-metadata","memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","error":"The group is rebalancing, so a rejoin is needed"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.196Z","logger":"kafkajs","message":"[Connection] Request GroupCoordinator(key: 10, version: 2)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":12,"expectResponse":true,"size":42}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.198Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.198Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.199Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.199Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.199Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.199Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.199Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.199Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[Runner] stop consumer group","groupId":"node-metadata","memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[FetchManager] Stopping fetchers..."}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[FetchManager] Stopped fetchers"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[Runner] waiting for consumer to finish...","groupId":"node-metadata","memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.200Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.201Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 2)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":12,"size":31,"data":{"throttleTime":0,"errorCode":0,"errorMessage":"NONE","coordinator":{"nodeId":1,"host":"kafka","port":9092},"clientSideThrottleTime":0}}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.201Z","logger":"kafkajs","message":"[Cluster] Found group coordinator","nodeId":1}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.201Z","logger":"kafkajs","message":"[Connection] Request JoinGroup(key: 11, version: 5)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":13,"expectResponse":true,"size":209}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.202Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.203Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka:9092","clientId":"1503bb242f7f"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.204Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 5)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":13,"size":392,"data":{"throttleTime":0,"clientSideThrottleTime":0,"errorCode":0,"generationId":2,"groupProtocol":"RoundRobinAssigner","leaderId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","members":[{"memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","groupInstanceId":null,"memberMetadata":{"type":"Buffer","data":[0,1,0,0,0,2,0,26,110,111,100,101,95,109,101,116,97,100,97,116,97,46,97,100,100,95,110,111,100,101,95,114,101,102,0,29,110,111,100,101,95,109,101,116,97,100,97,116,97,46,114,101,109,111,118,101,95,110,111,100,101,95,114,101,102,0,0,0,0]}},{"memberId":"58f86b1805fa-20ac2e10-4c4d-4a1b-9caa-c013cace4ac0","groupInstanceId":null,"memberMetadata":{"type":"Buffer","data":[0,1,0,0,0,2,0,26,110,111,100,101,95,109,101,116,97,100,97,116,97,46,97,100,100,95,110,111,100,101,95,114,101,102,0,29,110,111,100,101,95,109,101,116,97,100,97,116,97,46,114,101,109,111,118,101,95,110,111,100,101,95,114,101,102,0,0,0,0]}}]}}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.205Z","logger":"kafkajs","message":"[ConsumerGroup] Chosen as group leader","groupId":"node-metadata","generationId":2,"memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","topics":["node_metadata.add_node_ref","node_metadata.remove_node_ref"]}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.205Z","logger":"kafkajs","message":"[Connection] Request Metadata(key: 3, version: 6)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":14,"expectResponse":true,"size":90}
 {"level":"DEBUG","timestamp":"2022-05-24T11:45:51.209Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 6)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":14,"size":194,"data":{"throttleTime":0,"brokers":[{"nodeId":1,"host":"kafka","port":9092,"rack":null}],"clusterId":"n8o8LnnBTfOq1RnIYLl5Ug","controllerId":1,"topicMetadata":[{"topicErrorCode":0,"topic":"node_metadata.add_node_ref","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":0,"leader":1,"replicas":[1],"isr":[1],"offlineReplicas":[]}]},{"topicErrorCode":0,"topic":"node_metadata.remove_node_ref","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":0,"leader":1,"replicas":[1],"isr":[1],"offlineReplicas":[]}]}],"clientSideThrottleTime":0}}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.210Z","logger":"kafkajs","message":"[ConsumerGroup] Group assignment","groupId":"node-metadata","generationId":2,"groupProtocol":"RoundRobinAssigner","assignment":[{"memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","memberAssignment":{"type":"Buffer","data":[0,1,0,0,0,1,0,26,110,111,100,101,95,109,101,116,97,100,97,116,97,46,97,100,100,95,110,111,100,101,95,114,101,102,0,0,0,1,0,0,0,0,0,0,0,0]}},{"memberId":"58f86b1805fa-20ac2e10-4c4d-4a1b-9caa-c013cace4ac0","memberAssignment":{"type":"Buffer","data":[0,1,0,0,0,1,0,29,110,111,100,101,95,109,101,116,97,100,97,116,97,46,114,101,109,111,118,101,95,110,111,100,101,95,114,101,102,0,0,0,1,0,0,0,0,0,0,0,0]}}],"topics":["node_metadata.add_node_ref","node_metadata.remove_node_ref"]}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.210Z","logger":"kafkajs","message":"[Connection] Request SyncGroup(key: 14, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":15,"expectResponse":true,"size":307}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.213Z","logger":"kafkajs","message":"[Connection] Response SyncGroup(key: 14, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":15,"size":60,"data":{"throttleTime":0,"errorCode":0,"memberAssignment":{"type":"Buffer","data":[0,1,0,0,0,1,0,26,110,111,100,101,95,109,101,116,97,100,97,116,97,46,97,100,100,95,110,111,100,101,95,114,101,102,0,0,0,1,0,0,0,0,0,0,0,0]},"clientSideThrottleTime":0}}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.213Z","logger":"kafkajs","message":"[ConsumerGroup] Received assignment","groupId":"node-metadata","generationId":2,"memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","memberAssignment":{"node_metadata.add_node_ref":[0]}}
{"level":"INFO","timestamp":"2022-05-24T11:45:51.213Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"node-metadata","memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","leaderId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","isLeader":true,"memberAssignment":{"node_metadata.add_node_ref":[0]},"groupProtocol":"RoundRobinAssigner","duration":17}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.216Z","logger":"kafkajs","message":"[Connection] Request LeaveGroup(key: 13, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":16,"expectResponse":true,"size":98}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.224Z","logger":"kafkajs","message":"[Connection] Response LeaveGroup(key: 13, version: 3)","broker":"kafka:9092","clientId":"1503bb242f7f","correlationId":16,"size":69,"data":{"throttleTime":0,"clientSideThrottleTime":0,"errorCode":0,"members":[{"memberId":"1503bb242f7f-54a7c33b-7bdf-48f6-8e9e-234d5268074b","groupInstanceId":null,"errorCode":0}]}}
{"level":"INFO","timestamp":"2022-05-24T11:45:51.225Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"node-metadata"}
{"level":"DEBUG","timestamp":"2022-05-24T11:45:51.225Z","logger":"kafkajs","message":"[Consumer] consumer has stopped, disconnecting","groupId":"node-metadata"}

**Comment by Nevon** [comment]
Are you able to reproduce this locally? If you could put a breakpoint [right here](https://github.com/tulios/kafkajs/blob/master/src/broker/index.js#L413) so we can see what the callstack looks like, that might tell us what's causing the consumer to leave the group. Alternatively, you could just do a dirty patch like:

```js
async leaveGroup({ groupId, memberId }) {
    const error = new Error('Fake error to get a stack trace')
    this.logger.info('Leaving group', { groupId, memberId, stack: error.stack })

    const leaveGroup = this.lookupRequest(apiKeys.LeaveGroup, requests.LeaveGroup)
    return await this[PRIVATE.SEND_REQUEST](leaveGroup({ groupId, memberId }))
  }
```

**Comment by leppaott** [comment]
Ah thanks for the help! I found that the exiting originated from our code and LeaveGroup/disconnect was working fine.

Not the first time this shows problems but it was that we listen to Node 'multipleResolves' event and terminate if we get such.

> _`https://nodejs.org/api/process.html#event-multipleresolves`_
The 'multipleResolves' event is emitted whenever a Promise has been either:
Resolved more than once.
Rejected more than once.
Rejected after resolve.
Resolved after reject.

Here's that promise we get from the event hook:

> _Promise {
  <rejected> KafkaJSProtocolError: The group is rebalancing, so a rejoin is needed
      at createErrorFromCode (kafkajs/src/protocol/error.js:581:10)
      at Object.parse (kafkajs/src/protocol/requests/heartbeat/v0/response.js:20:11)
      at Connection.send (kafkajs/src/network/connection.js:433:35)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Broker.[private:Broker:sendRequest] (kafkajs/src/broker/index.js:878:14)
      at async Broker.heartbeat (kafkajs/src/broker/index.js:343:12)
      at async kafkajs/src/consumer/consumerGroup.js:144:9
      at async Runner.heartbeat (kafkajs/src/consumer/runner.js:173:7)
      at async onBatch (kafkajs/src/consumer/runner.js:382:9)
      at async kafkajs/src/consumer/runner.js:405:9 {
    retriable: false,
    helpUrl: 'https://kafka.js.org/docs/faq#what-does-it-mean-to-get-rebalance-in-progress-errors',
    type: 'REBALANCE_IN_PROGRESS',
    code: 27,
    [cause]: undefined
  }
}_

Maybe that can help find the exact location of that promise as this didn't happen on 1.6.0. But then again Node 17 deprecated it for the reason "This event was deprecated because it did not work with V8 promise combinators which diminished its usefulness." https://nodejs.org/api/deprecations.html#DEP0160 So yeah maybe we deprecate use of this as well.
